// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxmkmhatzkghkwfdlftf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4bWttaGF0emtnaGt3ZmRsZnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDY3ODksImV4cCI6MjA2NTUyMjc4OX0.mswyOHjBi3kegUaoC1sDVVqrkpMLgfpmbolOU-qgNC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);